services:
  swagger-ui:
    image: docker.swagger.io/swaggerapi/swagger-ui:latest
    container_name: iter_swagger_ui
    restart: unless-stopped
    depends_on:
      open-dpp-api:
        condition: service_healthy
    environment:
      SWAGGER_JSON: /swagger-ui/specification.yml
    networks:
      - public_network
    volumes:
      - ./open-api/docs/specification.yml:/swagger-ui/specification.yml

  open-dpp-api:
    image: ghcr.io/julesssssssssssss/iter-open-api:latest
    container_name: open_dpp_api
    restart: unless-stopped
    networks:
      - internal_network
      - public_network
    healthcheck:
      test: ['CMD-SHELL', 'wget -qO- http://127.0.0.1:7000/health || exit 1']
      interval: 10s
      timeout: 5s
      retries: 3

# Compose networks
networks:
  internal_network:
    driver: bridge
  public_network:
    external: true
