x-logging: &default-logging
  driver: json-file
  options:
    max-size: '10m'
    max-file: '3'

services:
  swagger-ui:
    image: docker.swagger.io/swaggerapi/swagger-ui:v5.32.8
    container_name: iter_swagger_ui
    restart: unless-stopped
    # depends_on:
    #   open-dpp-api:
    #     condition: service_healthy
    environment:
      SWAGGER_JSON: /swagger-ui/specification.yml
    ports:
      - 81:8080
    networks:
      - public_network
    volumes:
      - ./open-api/docs/specification.yml:/swagger-ui/specification.yml
    healthcheck:
      test: ['CMD-SHELL', 'wget -qO- http://127.0.0.1:8080/ || exit 1']
      interval: 10s
      timeout: 5s
      retries: 3
    logging: *default-logging

  open-dpp-api:
    build: ./open-api
    container_name: open_dpp_api
    restart: unless-stopped
    ports:
      - 80:7000
    networks:
      - internal_network
      - public_network
    depends_on:
      open-dpp-db:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'wget -qO- http://127.0.0.1:7000/health || exit 1']
      interval: 10s
      timeout: 5s
      retries: 3
    logging: *default-logging

  open-dpp-db:
    image: postgres:18
    restart: unless-stopped
    container_name: open_dpp_db
    env_file:
      - .env
    environment:
      DB_ENV: dev
    networks:
      - internal_network
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - open_dpp_pg:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 5s
      timeout: 5s
      retries: 5
    logging: *default-logging

# Compose networks
networks:
  internal_network:
    driver: bridge
  public_network:
    external: true

# Compose volumes
volumes:
  open_dpp_pg:
